version: "3.0"
services:
  wuxin-api:
    restart: always
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    networks:
      - wuxin_net
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_PASSWORD: "123456"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_DATABASE: "wuxin_db"
    restart: always
    volumes:
      - ./wuxin-app/mysql/db:/var/lib/mysql
      - ./wuxin-app/mysql/my.cnf:/etc/my.cnf
      - ./wuxin-app/mysql/init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - wuxin_net

  redis:
    image: redis:6.0
    ports:
      - "6379:6379"
    volumes:
      - ./wuxin-app/redis/redis.conf:/etc/redis/redis.conf
      - ./wuxin-app/redis/data:/data
    restart: always
    networks:
      - wuxin_net
    command: redis-server /etc/redis/redis.conf


  wuxin-front:
    container_name: wuxin-front
    restart: always
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - ./front/dist/:/usr/share/nginx/html/:ro
      - ./front/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    networks:
      - wuxin_net
    depends_on:
      - wuxin-api

  wuxin-admin:
    restart: always
    container_name: wuxin-admin
    build:
      context: ./admin
      dockerfile: Dockerfile
    volumes:
      - ./front/dist/:/usr/share/nginx/html/:ro
      - ./front/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    networks:
      - wuxin_net
    depends_on:
      - wuxin-api
networks:
  wuxin_net:
    driver: bridge
