#端口号
server:
  port: 8888
  servlet:
    context-path: /
spring:
  #  基本配置
  application:
    name: wuxin
  #  mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wuxin_db?useSSL=false&serverTimezone=GMT%2b8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    hikari:
      connection-init-sql: SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci
  #redis
  redis:
    host: localhost
    database: 5
    port: 6379
    password:
    jedis:
      pool:
        max-active: 50
        max-idle: 20
        min-idle: 5
        max-wait: 5
  # thymeleaf配置
  thymeleaf:
    encoding: utf-8
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTMl

  #  #    邮箱配置
  mail:
    protocol: smtp
    host: smtp.qq.com
    username: 2191377759@qq.com
    password: huxlzhjulymwdjhe
    default-encoding: UTF-8
  #  文件大小配置
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB

  #  日期格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  # banner 配置
  main:
    banner-mode: off

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /*
  # 匹配链接
  urlPatterns: /admin/*

#  mybatis-plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: wx


#web:
#  admin:
#    url: http://localhost:2768
#  url: http://localhost:8080